version: 2

models:
  - name: stg_members
    columns:
      - name: member_id
        data_tests:
          - unique
          - not_null
      - name: membership_tier
        data_tests:
          - accepted_values:
              arguments:
                values: ["Bronze", "Silver", "Gold"]
  - name: stg_books
    columns:
      - name: book_id
        data_tests:
          - unique
          - not_null
  - name: stg_loans
    columns:
      - name: loan_id
        data_tests:
          - unique
          - not_null
      - name: book_id
        data_tests:
          - relationships:
              to: ref('stg_books')
              field: book_id
      - name: member_id
        data_tests:
          - relationships:
              to: ref('stg_members')
              field: member_id
  - name: customer_withdrawals
    columns:
      - name: fee_applied
        data_tests:
          - no_negative_values
  - name: customers_with_late_fees
    data_tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('solucion')
    columns:
      - name: discount_applied
        data_tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 0.25

seeds:
  - name: solucion